### ISSUE TITLE
Reflectionにおける継承の扱いについて

### ISSUE THREAD

**Issue by akeit0** [AnnulusGames/Alchemy#2]
ReflectionHelperにおける継承の扱いなんですが、bool inheritで継承元まで探すか決めているところが多くありますが、
interfaceでなければ、BindingFlags.DeclaredOnlyを付けない限り、継承元まで探すはずです。

なので、GetAllPropertiesIncludingInheritedのような場所や、見つからなければ継承元で繰り返すような処理は必要なく、
逆に継承元まで探さないはずなのに、探すという状態になってしまっています。

以下は個人的リファクタリングの提案ですが、
```
FieldInfo info;
if (cacheFieldInfo.ContainsKey((type, name, bindingAttr, inherit)))
{
  info = cacheFieldInfo[(type, name, bindingAttr, inherit)];
}
else
```
などは、やはり
```
FieldInfo info;
if (!cacheFieldInfo.TryGetValue((type, name, bindingAttr, inherit), out info))
{
```
にしてほしいなという前にも別のところでした提案です。（書き方が好きじゃないとかであればいいですが）
あとSerializationHelperで
`if (IsUnityObject<T>)`
は
` if (target is UnityEngine.Object targetUnityObject)`にするとのちの as castもいらず、いいかなと思います

**Comment by AnnulusGames** [comment]
C#のReflectionは[基底クラスのprivate/internalを取得できない](https://learn.microsoft.com/ja-jp/dotnet/api/system.type.getfields?view=net-7.0)ため、これらを含めて取得したい場合は順に辿る必要があります。そもそも基底クラスのprivate/internalを取得すること自体が微妙ですが、こちらが含まれている方がShowIf等の属性では直感的な動作となるためこのような仕様にしています。引数の命名が悪いというのはあるんですが...

リファクタリングに関してはおっしゃる通りなので、次のバージョンに修正を含める予定です。(Lucid Editorのコードそのまま持ってきていたので修正を忘れてました...)

**Comment by AnnulusGames** [comment]
v1.0.2で該当部分のリファクタリングを行ったため、とりあえずこのIssueはクローズします。

**Comment by Akeit0** [comment]
これは独り言ですが、今の使い方だと結局全部探索するから
```
static readonly Dictionary<(Type, string), (MemberInfo, Func<object, object>)> cacheGetInfoAndGetter
```
系に集約してしまってもいいのではないかと思いました

**Comment by Akeit0** [comment]
独り言です。以下どちらでもいいことです。
用途的にも
```
static readonly Dictionary<(Type, string), (MemberInfo,Func<object, object>)> cacheGetInfoAndGetter
```
系に統一してしまったりしてもいいのかなと思ったり、
継承元で探す場合はPublicが二重になるので、BindingFlags.Publicを使わない方が、いいと思いました。

**Comment by Akeit0** [comment]
現在の継承元含めて検索でGetMembers系が遅延実行されていないので、遅延実行バージョンを貼っておきます
```cs
static IEnumerable<MethodInfo> GetAllMethodsIncludingBaseNonPublic(Type type, BindingFlags bindingAttr = BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static) {
    while (type != null) {
       foreach (var m in type.GetMethods(bindingAttr)) {
            yield return m;
        }
        type = type.BaseType;
        bindingAttr &=~BindingFlags.Public;
    }
}
```
