### ISSUE TITLE
Not Serializing corectly when inhertiting from abstract class

### ISSUE THREAD

**Issue by centhoang** [AnnulusGames/Alchemy#54]
![image](https://github.com/AnnulusGames/Alchemy/assets/45512245/92475722-4ffa-46a8-b7bf-f26a26d9a9be)
![image](https://github.com/AnnulusGames/Alchemy/assets/45512245/912ab944-b0f7-4e10-9730-ab85396d06f8)

the LockFlag field is an Alchemy Serialized field in a parent abstract class

**Comment by centhoang** [comment]
is there still any issues that blocking your forked branch from merging into main @Akeit0 ?

**Comment by AnnulusGames** [comment]
It's just that I'm late in checking...(I'd like to merge it once I've done some tests, but I'm currently working on another project so I don't have much time... )
I would like to respond to PR and other issues in the near future.

**Comment by lgarczyn** [comment]
Still an issue for me:

This works fine
```cs
[AlchemySerialize]
public partial class Test : MonoBehaviour
{
    [AlchemySerializeField, NonSerialized]
    public Vector3? nullable = null;
    [AlchemySerializeField, NonSerialized]
    public Dictionary<Vector3Int?, SOResource> testDic = null;

    [Button] public void TestButton()
    {
        Debug.Log("Test button clicked");
        // TestQueryQuery(ECSWorlds.Graph);
    }

    [Query]
    [All(typeof(EntityName))]
    public void TestQuery(ref EntityName eName)
    {
        Debug.Log(eName);
    }
}

```

But this doesn't
```cs
[AlchemySerialize]
public partial class Test : GameComponent
{
    [AlchemySerializeField, NonSerialized]
    public Vector3? nullable = null;
    [AlchemySerializeField, NonSerialized]
    public Dictionary<Vector3Int?, SOResource> testDic = null;

    [Button] public void TestButton()
    {
        Debug.Log("Test button clicked");
        // TestQueryQuery(ECSWorlds.Graph);
    }

    [Query]
    [All(typeof(EntityName))]
    public void TestQuery(ref EntityName eName)
    {
        Debug.Log(eName);
    }
}

// in another asmdef
public abstract class GameComponent : MonoBehaviour
{
   //...
}
```

**Comment by lgarczyn** [comment]
It might be another issue, since changing GameComponent to not be abstract doesn't fix the situation

**Comment by lgarczyn** [comment]
Nevermind, GameComponent had a custom editor that blocked the Alchemy one
