### ISSUE TITLE
List field not working in Scriptable Objects with Alchemy enabled

### ISSUE THREAD

**Issue by EricBatlle** [AnnulusGames/Alchemy#92]
Hey, I will really like to use this Editor Extension as it allows me to use [Button] attribute with parameters on methods, but I'm having the following issue with Lists:

To reproduce:

```
using UnityEngine;
using Alchemy.Inspector;
using System.Collections.Generic;

namespace CookingMarness
	{
		[CreateAssetMenu(fileName = "Test", menuName = "ScriptableObjects/Test")]
		public class TestSO : ScriptableObject
		{
			public List<int> Test = new List<int>();

			private void Reset()
			{
				Test?.Clear();
			}

			[Button]
			public void Add()
			{
				Test.Add(1);
			}
			[Button]
			public void Remove()
			{
				Test.Remove(1);
			}
		}
	}
}
```

It can get that behaviour:
![image](https://github.com/AnnulusGames/Alchemy/assets/15261880/a4f16d8d-d755-47ba-9427-3bc40721b599)

And also if you remove elements from the list, thows errors arise:
![image](https://github.com/AnnulusGames/Alchemy/assets/15261880/1db61e90-e034-44a0-bf34-c869c3cf316a)

**Comment by KiyoK7227** [comment]
Hello.

I am not sure about the problem when executing the function Add, as I have not been able to reproduce it, but for the function Remove, I think you can avoid the error by doing the following.

```
[Button]
public void Remove()
{
  if (Test.Count > 0)
  {
    Test.RemoveAt(Test.Count - 1);
  }
}
```
